using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace DanbaidongShaderConverter
{
    public static class ShaderConversionReport
    {
        public static string GenerateReport(List<ConversionResult> results, List<ShaderFileInfo> allFiles)
        {
            string timestamp = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
            string dir = "Assets/Editor/DanbaidongShaderConverter/Reports";
            Directory.CreateDirectory(dir);
            string path = Path.Combine(dir, $"ConversionReport_{timestamp}.md");

            using var writer = new StreamWriter(path);

            writer.WriteLine("# Danbaidong Shader Conversion Report");
            writer.WriteLine($"**Generated**: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            writer.WriteLine();

            // Summary
            int converted = 0, skipped = 0, errors = 0, totalChanges = 0;
            foreach (var r in results)
            {
                if (r.HasError) errors++;
                else if (r.WasConverted) { converted++; totalChanges += r.ChangesCount; }
                else skipped++;
            }

            writer.WriteLine("## Summary");
            writer.WriteLine($"- **Total files scanned**: {allFiles.Count}");
            writer.WriteLine($"- **Converted**: {converted}");
            writer.WriteLine($"- **Skipped**: {skipped}");
            writer.WriteLine($"- **Errors**: {errors}");
            writer.WriteLine($"- **Total path replacements**: {totalChanges}");
            writer.WriteLine();

            // Scan overview
            writer.WriteLine("## Scan Results by Category");
            writer.WriteLine();
            writer.WriteLine("| Category | Count | Needs Conversion |");
            writer.WriteLine("|----------|-------|------------------|");

            foreach (ShaderCategory cat in Enum.GetValues(typeof(ShaderCategory)))
            {
                int count = allFiles.FindAll(f => f.Category == cat).Count;
                if (count > 0)
                {
                    bool needs = allFiles.Exists(f => f.Category == cat && f.NeedsConversion);
                    string name = ShaderScanEngine.GetCategoryDisplayName(cat);
                    writer.WriteLine($"| {name} | {count} | {(needs ? "Yes" : "No")} |");
                }
            }
            writer.WriteLine();

            // Detailed results
            if (results.Count > 0)
            {
                writer.WriteLine("## Conversion Details");
                writer.WriteLine();

                foreach (var r in results)
                {
                    string status = r.HasError ? "ERROR" : (r.WasConverted ? "CONVERTED" : "SKIPPED");
                    writer.WriteLine($"### [{status}] {Path.GetFileName(r.FilePath)}");
                    writer.WriteLine($"- Path: `{r.FilePath}`");
                    writer.WriteLine($"- Category: {ShaderScanEngine.GetCategoryDisplayName(r.Category)}");
                    writer.WriteLine($"- Changes: {r.ChangesCount}");
                    if (!string.IsNullOrEmpty(r.BackupPath))
                        writer.WriteLine($"- Backup: `{r.BackupPath}`");
                    if (!string.IsNullOrEmpty(r.Details))
                    {
                        writer.WriteLine("- Details:");
                        foreach (var line in r.Details.Split('\n'))
                            writer.WriteLine($"  - {line}");
                    }
                    writer.WriteLine();
                }
            }

            // All scanned files
            writer.WriteLine("## All Scanned Files");
            writer.WriteLine();
            writer.WriteLine("| File | Category | Convertible |");
            writer.WriteLine("|------|----------|-------------|");
            foreach (var f in allFiles)
            {
                string name = Path.GetFileName(f.FilePath);
                string cat = ShaderScanEngine.GetCategoryDisplayName(f.Category);
                string conv = f.NeedsConversion ? "Yes" : "No";
                writer.WriteLine($"| {name} | {cat} | {conv} |");
            }

            writer.WriteLine();
            writer.WriteLine("---");
            writer.WriteLine("*Generated by Danbaidong Shader Converter*");

            return path;
        }
    }
}
